import type { ColumnDef, Job, JobStatus } from '@/types';

/* ── column definitions ─────────────────────────────────── */
export const COLUMNS: ColumnDef[] = [
  { id: 'wishlist',  title: 'Wishlist',   color: '#64748b', icon: '✨' },
  { id: 'applied',   title: 'Applied',    color: '#3b82f6', icon: '📨' },
  { id: 'interview', title: 'Interview',  color: '#f59e0b', icon: '🎤' },
  { id: 'offer',     title: 'Offer',      color: '#22c55e', icon: '🎉' },
  { id: 'rejected',  title: 'Rejected',   color: '#ef4444', icon: '❌' },
];

export const STATUS_OPTIONS: { value: JobStatus; label: string }[] = [
  { value: 'wishlist',  label: 'Wishlist' },
  { value: 'applied',   label: 'Applied' },
  { value: 'interview', label: 'Interview' },
  { value: 'offer',     label: 'Offer' },
  { value: 'rejected',  label: 'Rejected' },
];

/* ── seed data shown in demo mode ───────────────────────── */
export const DEMO_JOBS: Job[] = [
  {
    id: 'demo-1',
    company: 'Stripe',
    role: 'Senior Frontend Engineer',
    salary_min: 180000,
    salary_max: 220000,
    status: 'interview',
    date_applied: '2026-02-28',
    notes: 'Phone screen went well. Technical round next week with the payments team.',
    contact_name: 'Sarah Chen',
    contact_email: 'sarah.chen@stripe.com',
    url: 'https://stripe.com/jobs/senior-fe',
    tags: ['react', 'typescript', 'fintech'],
    position: 0,
    created_at: '2026-02-25T10:00:00Z',
    updated_at: '2026-03-05T14:30:00Z',
  },
  {
    id: 'demo-2',
    company: 'Vercel',
    role: 'Full Stack Developer',
    salary_min: 160000,
    salary_max: 200000,
    status: 'applied',
    date_applied: '2026-03-10',
    notes: 'Applied through their careers page. Love the Next.js ecosystem.',
    contact_name: null,
    contact_email: null,
    url: 'https://vercel.com/careers',
    tags: ['next.js', 'react', 'edge'],
    position: 0,
    created_at: '2026-03-10T09:00:00Z',
    updated_at: '2026-03-10T09:00:00Z',
  },
  {
    id: 'demo-3',
    company: 'Linear',
    role: 'Product Engineer',
    salary_min: 150000,
    salary_max: 190000,
    status: 'wishlist',
    date_applied: null,
    notes: 'Dream company. Their app is incredible. Need to prep portfolio first.',
    contact_name: null,
    contact_email: null,
    url: 'https://linear.app/careers',
    tags: ['react', 'typescript', 'product'],
    position: 0,
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-03-01T12:00:00Z',
  },
  {
    id: 'demo-4',
    company: 'Shopify',
    role: 'Frontend Developer',
    salary_min: 140000,
    salary_max: 180000,
    status: 'applied',
    date_applied: '2026-03-08',
    notes: 'Referral from Alex. Applied to the Checkout team.',
    contact_name: 'Alex Kim',
    contact_email: 'alex.k@shopify.com',
    url: 'https://shopify.com/careers',
    tags: ['react', 'graphql', 'ecommerce'],
    position: 1,
    created_at: '2026-03-08T15:00:00Z',
    updated_at: '2026-03-08T15:00:00Z',
  },
  {
    id: 'demo-5',
    company: 'Notion',
    role: 'Software Engineer',
    salary_min: 170000,
    salary_max: 210000,
    status: 'interview',
    date_applied: '2026-02-20',
    notes: 'System design round completed. Waiting for the final panel.',
    contact_name: 'Jamie Lee',
    contact_email: 'jamie@notion.so',
    url: 'https://notion.so/careers',
    tags: ['react', 'typescript', 'collaboration'],
    position: 1,
    created_at: '2026-02-18T10:00:00Z',
    updated_at: '2026-03-12T16:00:00Z',
  },
  {
    id: 'demo-6',
    company: 'Figma',
    role: 'UI Engineer',
    salary_min: 175000,
    salary_max: 215000,
    status: 'offer',
    date_applied: '2026-02-10',
    notes: '🎉 Offer received! $195k base + equity. Need to respond by March 20.',
    contact_name: 'Maria Santos',
    contact_email: 'maria@figma.com',
    url: 'https://figma.com/careers',
    tags: ['react', 'canvas', 'design-tools'],
    position: 0,
    created_at: '2026-02-08T10:00:00Z',
    updated_at: '2026-03-13T09:00:00Z',
  },
  {
    id: 'demo-7',
    company: 'Netflix',
    role: 'Senior UI Engineer',
    salary_min: 200000,
    salary_max: 250000,
    status: 'rejected',
    date_applied: '2026-01-15',
    notes: 'Rejected after technical round. Feedback: needed more experience with large-scale streaming apps.',
    contact_name: null,
    contact_email: null,
    url: 'https://jobs.netflix.com',
    tags: ['react', 'performance', 'streaming'],
    position: 0,
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'demo-8',
    company: 'Supabase',
    role: 'Frontend Engineer',
    salary_min: 150000,
    salary_max: 185000,
    status: 'wishlist',
    date_applied: null,
    notes: 'Open-source company using their own product. Would be awesome to contribute.',
    contact_name: null,
    contact_email: null,
    url: 'https://supabase.com/careers',
    tags: ['react', 'supabase', 'open-source'],
    position: 1,
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-03-05T10:00:00Z',
  },
];
