import type { Course } from "@/types";

export const COURSES: Course[] = [
  /* ══════════════════════════════════════════════════════
     TECHNOLOGY
     ══════════════════════════════════════════════════════ */
  {
    id: "course-1",
    title: "HTML & CSS for Beginners",
    provider: "freeCodeCamp",
    difficulty: "beginner",
    duration: "6 hours",
    url: "https://freecodecamp.org",
    skillIds: ["html", "css"],
    description:
      "Learn the fundamentals of HTML structure and CSS styling from scratch.",
    rating: 4.8,
    isFree: true,
  },
  {
    id: "course-2",
    title: "Advanced CSS and Sass",
    provider: "Udemy",
    difficulty: "intermediate",
    duration: "28 hours",
    url: "https://udemy.com",
    skillIds: ["css", "responsive-design"],
    description:
      "Master flexbox, grid, animations, and responsive design patterns.",
    rating: 4.7,
    isFree: false,
  },
  {
    id: "course-3",
    title: "JavaScript: The Complete Guide",
    provider: "Udemy",
    difficulty: "beginner",
    duration: "52 hours",
    url: "https://udemy.com",
    skillIds: ["javascript"],
    description:
      "Comprehensive JavaScript course from basics to advanced concepts.",
    rating: 4.6,
    isFree: false,
  },
  {
    id: "course-4",
    title: "TypeScript for Professionals",
    provider: "Coursera",
    difficulty: "intermediate",
    duration: "20 hours",
    url: "https://coursera.org",
    skillIds: ["typescript"],
    description:
      "Learn the TypeScript type system, generics, and advanced patterns.",
    rating: 4.5,
    isFree: false,
  },
  {
    id: "course-5",
    title: "React — The Complete Guide",
    provider: "Udemy",
    difficulty: "intermediate",
    duration: "48 hours",
    url: "https://udemy.com",
    skillIds: ["react", "javascript", "typescript"],
    description:
      "Build modern React applications with hooks, context, and Next.js.",
    rating: 4.7,
    isFree: false,
  },
  {
    id: "course-6",
    title: "Full Stack Open",
    provider: "University of Helsinki",
    difficulty: "intermediate",
    duration: "100+ hours",
    url: "https://fullstackopen.com",
    skillIds: ["react", "nodejs", "rest-apis", "testing", "typescript"],
    description:
      "Deep dive into modern web development with React and Node.js.",
    rating: 4.9,
    isFree: true,
  },
  {
    id: "course-7",
    title: "Node.js — The Complete Guide",
    provider: "Udemy",
    difficulty: "intermediate",
    duration: "36 hours",
    url: "https://udemy.com",
    skillIds: ["nodejs", "rest-apis", "javascript"],
    description:
      "Build scalable backend services with Node.js, Express, and MongoDB.",
    rating: 4.6,
    isFree: false,
  },
  {
    id: "course-8",
    title: "SQL for Data Science",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "15 hours",
    url: "https://coursera.org",
    skillIds: ["sql"],
    description: "Learn SQL querying, joins, aggregations, and subqueries.",
    rating: 4.5,
    isFree: false,
  },
  {
    id: "course-9",
    title: "Python for Everybody",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "30 hours",
    url: "https://coursera.org",
    skillIds: ["python"],
    description:
      "Learn Python programming from scratch with practical exercises.",
    rating: 4.8,
    isFree: true,
  },
  {
    id: "course-10",
    title: "Git & GitHub Crash Course",
    provider: "YouTube",
    difficulty: "beginner",
    duration: "2 hours",
    url: "https://youtube.com",
    skillIds: ["git"],
    description:
      "Learn version control basics, branching, merging, and collaboration.",
    rating: 4.7,
    isFree: true,
  },
  {
    id: "course-11",
    title: "Docker & Kubernetes: The Practical Guide",
    provider: "Udemy",
    difficulty: "intermediate",
    duration: "24 hours",
    url: "https://udemy.com",
    skillIds: ["docker", "kubernetes"],
    description: "Containerize applications and orchestrate with Kubernetes.",
    rating: 4.7,
    isFree: false,
  },
  {
    id: "course-12",
    title: "AWS Cloud Practitioner",
    provider: "AWS",
    difficulty: "beginner",
    duration: "12 hours",
    url: "https://aws.amazon.com/training",
    skillIds: ["cloud-aws"],
    description: "Understand AWS cloud fundamentals and core services.",
    rating: 4.6,
    isFree: true,
  },
  {
    id: "course-13",
    title: "Testing JavaScript",
    provider: "TestingJavaScript.com",
    difficulty: "intermediate",
    duration: "18 hours",
    url: "https://testingjavascript.com",
    skillIds: ["testing", "javascript"],
    description:
      "Learn unit testing, integration testing, and E2E with Jest and Cypress.",
    rating: 4.8,
    isFree: false,
  },
  {
    id: "course-14",
    title: "Google UX Design Certificate",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "70 hours",
    url: "https://coursera.org",
    skillIds: [
      "user-research",
      "wireframing",
      "prototyping",
      "figma",
      "design-thinking",
    ],
    description:
      "Complete UX design program from research to high-fidelity prototypes.",
    rating: 4.8,
    isFree: false,
  },
  {
    id: "course-15",
    title: "Data Visualization with Tableau",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "10 hours",
    url: "https://coursera.org",
    skillIds: ["data-visualization", "data-analysis"],
    description:
      "Create compelling visualizations and dashboards with Tableau.",
    rating: 4.4,
    isFree: false,
  },
  {
    id: "course-16",
    title: "CI/CD with GitHub Actions",
    provider: "YouTube",
    difficulty: "intermediate",
    duration: "4 hours",
    url: "https://youtube.com",
    skillIds: ["ci-cd", "git"],
    description:
      "Automate testing, building, and deployment with GitHub Actions.",
    rating: 4.5,
    isFree: true,
  },
  {
    id: "course-17",
    title: "Statistics and Probability",
    provider: "Khan Academy",
    difficulty: "beginner",
    duration: "15 hours",
    url: "https://khanacademy.org",
    skillIds: ["statistics", "critical-thinking"],
    description:
      "Master fundamental statistics concepts with interactive exercises.",
    rating: 4.7,
    isFree: true,
  },
  {
    id: "course-18",
    title: "Linux Command Line Basics",
    provider: "Udacity",
    difficulty: "beginner",
    duration: "8 hours",
    url: "https://udacity.com",
    skillIds: ["linux", "scripting"],
    description: "Get comfortable with the Linux terminal and shell scripting.",
    rating: 4.5,
    isFree: true,
  },
  {
    id: "course-19",
    title: "Monitoring and Observability",
    provider: "Udemy",
    difficulty: "intermediate",
    duration: "14 hours",
    url: "https://udemy.com",
    skillIds: ["monitoring", "docker"],
    description:
      "Learn Prometheus, Grafana, and modern observability practices.",
    rating: 4.4,
    isFree: false,
  },

  /* ══════════════════════════════════════════════════════
     BANKING & FINANCE
     ══════════════════════════════════════════════════════ */
  {
    id: "course-20",
    title: "Financial Markets",
    provider: "Coursera (Yale)",
    difficulty: "beginner",
    duration: "33 hours",
    url: "https://coursera.org",
    skillIds: ["financial-literacy", "economics", "risk-management"],
    description:
      "Robert Shiller's renowned course on how financial markets work.",
    rating: 4.8,
    isFree: true,
  },
  {
    id: "course-21",
    title: "Financial Modelling & Valuation",
    provider: "CFI",
    difficulty: "intermediate",
    duration: "40 hours",
    url: "https://corporatefinanceinstitute.com",
    skillIds: ["financial-modelling", "excel", "accounting"],
    description: "Build DCF, comparable, and LBO models in Excel from scratch.",
    rating: 4.7,
    isFree: false,
  },
  {
    id: "course-22",
    title: "Introduction to Accounting",
    provider: "Coursera (UPenn)",
    difficulty: "beginner",
    duration: "15 hours",
    url: "https://coursera.org",
    skillIds: ["accounting", "financial-literacy"],
    description:
      "Learn financial statements, balance sheets, and the accounting cycle.",
    rating: 4.6,
    isFree: true,
  },
  {
    id: "course-23",
    title: "Risk Management in Banking",
    provider: "edX",
    difficulty: "intermediate",
    duration: "24 hours",
    url: "https://edx.org",
    skillIds: [
      "risk-management",
      "regulatory-compliance",
      "financial-literacy",
    ],
    description: "Understand credit, market, and operational risk frameworks.",
    rating: 4.5,
    isFree: false,
  },
  {
    id: "course-24",
    title: "Excel Skills for Business",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "20 hours",
    url: "https://coursera.org",
    skillIds: ["excel"],
    description:
      "Master spreadsheets, formulas, pivot tables, and data analysis.",
    rating: 4.6,
    isFree: false,
  },

  /* ══════════════════════════════════════════════════════
     BUSINESS & CONSULTING
     ══════════════════════════════════════════════════════ */
  {
    id: "course-25",
    title: "Business Strategy Specialization",
    provider: "Coursera (UVA)",
    difficulty: "intermediate",
    duration: "30 hours",
    url: "https://coursera.org",
    skillIds: ["business-strategy", "critical-thinking", "data-analysis"],
    description: "Develop strategic thinking skills for business leadership.",
    rating: 4.6,
    isFree: false,
  },
  {
    id: "course-26",
    title: "Google Project Management Certificate",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "50 hours",
    url: "https://coursera.org",
    skillIds: ["project-management", "agile", "communication", "leadership"],
    description:
      "Learn project management fundamentals with real-world scenarios.",
    rating: 4.8,
    isFree: false,
  },
  {
    id: "course-27",
    title: "Product Management Fundamentals",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "25 hours",
    url: "https://coursera.org",
    skillIds: ["product-strategy", "agile", "data-analysis", "user-research"],
    description:
      "Learn product lifecycle, roadmapping, and agile methodologies.",
    rating: 4.6,
    isFree: false,
  },
  {
    id: "course-28",
    title: "Presentation Skills: Speechless",
    provider: "Udemy",
    difficulty: "beginner",
    duration: "6 hours",
    url: "https://udemy.com",
    skillIds: ["presentation", "communication"],
    description: "Master the art of presenting ideas clearly and persuasively.",
    rating: 4.5,
    isFree: false,
  },
  {
    id: "course-29",
    title: "Business Writing & Report Crafting",
    provider: "LinkedIn Learning",
    difficulty: "beginner",
    duration: "8 hours",
    url: "https://linkedin.com/learning",
    skillIds: ["report-writing", "communication", "attention-to-detail"],
    description:
      "Write clear emails, memos, proposals, and professional reports.",
    rating: 4.4,
    isFree: false,
  },

  /* ══════════════════════════════════════════════════════
     MARKETING & SALES
     ══════════════════════════════════════════════════════ */
  {
    id: "course-30",
    title: "Google Digital Marketing & E-Commerce",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "60 hours",
    url: "https://coursera.org",
    skillIds: ["digital-marketing", "seo-sem", "social-media", "data-analysis"],
    description:
      "Full Google certificate covering digital marketing, SEO, and analytics.",
    rating: 4.7,
    isFree: false,
  },
  {
    id: "course-31",
    title: "The Strategy of Content Marketing",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "18 hours",
    url: "https://coursera.org",
    skillIds: ["copywriting", "marketing-strategy", "social-media"],
    description:
      "Learn to create and distribute compelling content that converts.",
    rating: 4.5,
    isFree: true,
  },
  {
    id: "course-32",
    title: "Sales Training: Practical Sales Techniques",
    provider: "Udemy",
    difficulty: "beginner",
    duration: "10 hours",
    url: "https://udemy.com",
    skillIds: ["sales-negotiation", "client-management", "communication"],
    description: "Practical sales skills from prospecting to closing deals.",
    rating: 4.6,
    isFree: false,
  },
  {
    id: "course-33",
    title: "HubSpot CRM & Inbound Sales",
    provider: "HubSpot Academy",
    difficulty: "beginner",
    duration: "6 hours",
    url: "https://academy.hubspot.com",
    skillIds: ["crm-tools", "client-management", "digital-marketing"],
    description: "Master CRM tools and inbound sales methodology with HubSpot.",
    rating: 4.6,
    isFree: true,
  },
  {
    id: "course-34",
    title: "Market Research & Consumer Behaviour",
    provider: "Coursera",
    difficulty: "intermediate",
    duration: "20 hours",
    url: "https://coursera.org",
    skillIds: ["market-research", "data-analysis", "critical-thinking"],
    description:
      "Understand consumer behaviour and conduct effective market research.",
    rating: 4.4,
    isFree: false,
  },

  /* ══════════════════════════════════════════════════════
     HUMAN RESOURCES
     ══════════════════════════════════════════════════════ */
  {
    id: "course-35",
    title: "Human Resource Management (SHRM)",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "22 hours",
    url: "https://coursera.org",
    skillIds: [
      "hr-management",
      "recruitment",
      "communication",
      "conflict-resolution",
    ],
    description:
      "Learn the fundamentals of HR practices, policies, and talent management.",
    rating: 4.5,
    isFree: false,
  },
  {
    id: "course-36",
    title: "Recruiting & Talent Acquisition",
    provider: "LinkedIn Learning",
    difficulty: "beginner",
    duration: "8 hours",
    url: "https://linkedin.com/learning",
    skillIds: ["recruitment", "communication", "social-media"],
    description:
      "Source, screen, and hire talent effectively using modern tools.",
    rating: 4.4,
    isFree: false,
  },
  {
    id: "course-37",
    title: "Introduction to Labour Law",
    provider: "edX",
    difficulty: "beginner",
    duration: "12 hours",
    url: "https://edx.org",
    skillIds: ["labour-law", "regulatory-compliance"],
    description:
      "Understand employment law, contracts, and workplace regulations.",
    rating: 4.3,
    isFree: true,
  },

  /* ══════════════════════════════════════════════════════
     HEALTHCARE
     ══════════════════════════════════════════════════════ */
  {
    id: "course-38",
    title: "Healthcare Management",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "20 hours",
    url: "https://coursera.org",
    skillIds: ["healthcare-systems", "leadership", "project-management"],
    description:
      "Learn hospital operations, quality management, and healthcare policy.",
    rating: 4.5,
    isFree: false,
  },
  {
    id: "course-39",
    title: "Epidemiology & Public Health",
    provider: "Coursera (Johns Hopkins)",
    difficulty: "beginner",
    duration: "16 hours",
    url: "https://coursera.org",
    skillIds: [
      "healthcare-systems",
      "statistics",
      "research-methods",
      "data-analysis",
    ],
    description:
      "Study disease patterns, public health interventions, and data methods.",
    rating: 4.7,
    isFree: true,
  },

  /* ══════════════════════════════════════════════════════
     EDUCATION
     ══════════════════════════════════════════════════════ */
  {
    id: "course-40",
    title: "Instructional Design Foundations",
    provider: "LinkedIn Learning",
    difficulty: "beginner",
    duration: "10 hours",
    url: "https://linkedin.com/learning",
    skillIds: ["instructional-design", "curriculum-planning", "communication"],
    description:
      "Design effective learning experiences using proven instructional models.",
    rating: 4.5,
    isFree: false,
  },

  /* ══════════════════════════════════════════════════════
     PUBLIC SERVICE & NGO
     ══════════════════════════════════════════════════════ */
  {
    id: "course-41",
    title: "Public Policy Analysis",
    provider: "edX",
    difficulty: "intermediate",
    duration: "18 hours",
    url: "https://edx.org",
    skillIds: [
      "policy-analysis",
      "research-methods",
      "report-writing",
      "critical-thinking",
    ],
    description:
      "Analyse policy problems and evaluate interventions using evidence.",
    rating: 4.4,
    isFree: true,
  },
  {
    id: "course-42",
    title: "Monitoring & Evaluation for Development",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "14 hours",
    url: "https://coursera.org",
    skillIds: [
      "project-management",
      "data-analysis",
      "report-writing",
      "stakeholder-engagement",
    ],
    description: "Design M&E frameworks for development and NGO projects.",
    rating: 4.5,
    isFree: true,
  },

  /* ══════════════════════════════════════════════════════
     CROSS-INDUSTRY SOFT SKILLS
     ══════════════════════════════════════════════════════ */
  {
    id: "course-43",
    title: "Communication Skills for Professionals",
    provider: "LinkedIn Learning",
    difficulty: "beginner",
    duration: "5 hours",
    url: "https://linkedin.com/learning",
    skillIds: ["communication", "presentation"],
    description:
      "Improve professional communication, presentations, and stakeholder management.",
    rating: 4.3,
    isFree: false,
  },
  {
    id: "course-44",
    title: "Leadership & Management",
    provider: "Coursera (Michigan)",
    difficulty: "intermediate",
    duration: "25 hours",
    url: "https://coursera.org",
    skillIds: [
      "leadership",
      "communication",
      "conflict-resolution",
      "stakeholder-engagement",
    ],
    description:
      "Develop leadership skills for managing teams and driving results.",
    rating: 4.6,
    isFree: false,
  },
  {
    id: "course-45",
    title: "Research Methods for Beginners",
    provider: "Coursera",
    difficulty: "beginner",
    duration: "12 hours",
    url: "https://coursera.org",
    skillIds: ["research-methods", "critical-thinking", "report-writing"],
    description:
      "Learn qualitative and quantitative research design and analysis.",
    rating: 4.4,
    isFree: true,
  },
  {
    id: "course-46",
    title: "Economics for Non-Economists",
    provider: "edX",
    difficulty: "beginner",
    duration: "18 hours",
    url: "https://edx.org",
    skillIds: ["economics", "critical-thinking"],
    description:
      "Understand micro and macro economics without a finance background.",
    rating: 4.5,
    isFree: true,
  },
];
